surfboard_inventory/models.py
from flask_sqlalchemy import SQLAlchemy 
from flask_migrate import Migrate
import uuid 
from datetime import datetime

# adding flask security for passwords
from werkzeug.security import generate_password_hash, check_password_hash

# import for secrets module (given by python)
import secrets 
# Imports for Flask_Login
from flask_login import UserMixin, LoginManager

# Import for Flask-Marshmallow
from flask_marshmallow import Marshmallow

db = SQLAlchemy()
login_manager = LoginManager()
ma = Marshmallow()
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

class User(db.Model):
    id = db.Column(db.String, primary_key = True)
    first_name = db.Column(db.String(150), nullable = True, default = '')
    last_name = db.Column(db.String(150), nullable = True, default = '')
    email = db.Column(db.String(150), nullable = False)
    password = db.Column(db.String, nullable = True, default = '')
    g_auth_verify = db.Column(db.Boolean,default = False) 
    token = db.Column(db.String, default = '', unique = True)
    date_create = db.Column(db.DateTime, nullable = False, default = datetime.utcnow)

    surfboard = db.relationship('Surfboard', backref = 'owner', lazy = True)
    

    def __init__(self, email, first_name = '', last_name = '', id = '', password = '', token = '',   g_auth_verify = False):
        self.id = self.set_id()
        self.first_name = first_name
        self.last_name = last_name
        self.password = self.set_password(password)
        self.email = email
        self.token = self.set_token(24)
        self.g_auth_verify = g_auth_verify
    def set_token(self, length):
        return secrets.token_hex(length)
    
    def set_id(self):
        return str(uuid.uuid4()) # the number 4 reps a different version. 1,3,4,5 do different things
    def set_password(self, password):
        self.pw_hash = generate_password_hash(password)
        return self.pw_hash
    
    def __repr__(self):
        return f"User {self.email} has been added to the database"
    

class Surfboard(db.Model, UserMixin):
    id = db.Column(db.String, primary_key=True)
    name = db.Column(db.String(150))
    description = db.Column(db.String(200))
    price = db.Column(db.Numeric(precision=10, scale=2))
    included_accessories = db.Column(db.String(150), nullable = True)
    base_color = db.Column(db.String(100), nullable = True)
    material = db.Column(db.String(100))
    dimensions = db.Column(db.String(100))
    weight = db.Column(db.String(100))
    cost_of_production = db.Column(db.Numeric(precision=10, scale=2))
    series = db.Column(db.String(150))
    user_token = db.Column(db.String, db.ForeignKey('user.token'), nullable = False)

    def __init__(self, name, description, price, included_accessories, base_color, material, dimensions, weight, cost_of_production, series, user_token, id = ''):
            self.id = self.set_id()
            self.name = name
            self.description = description 
            self.price = price
            self.included_accessories = included_accessories
            self.base_color = base_color
            self.material = material 
            self.dimensions = dimensions
            self.weight = weight
            self.cost_of_production = cost_of_production
            self.series = series
            self.user_token = user_token

    def __repr__(self):
            return f"The following Surfboard has been added: {self.name}"
    
    def set_id(self):
        return secrets.token_urlsafe()

class SurfboardSchema(ma.Schema):
    class Meta: 
        fields = ['id', 'name', 'description', 'price', 'included_accessories', 'base_color', 'material', 'dimensions', 'weight', 'cost_of_production', 'series']

surfboard_schema = SurfboardSchema()
surfboards_schema= SurfboardSchema(many = True)

surfboard_inventory/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email 



class UserLoginForm(FlaskForm):
    email = StringField('Email', validators = [DataRequired(), Email()])
    password = PasswordField('Password', validators = [DataRequired()])
    submit_button = SubmitField()

surfboard_inventory/__init__.py
from flask import Flask
from.site.routes import site
from config import Config
from .authentication.routes import auth

from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from .models import db as root_db

# Imports from Models
from .models import db as root_db, login_manager, ma

# Import Flask-Marshamllow
from flask_marshmallow import Marshmallow

#Flask-Cors Import
from flask_cors import CORS


app = Flask(__name__)
app.register_blueprint(site)
app.register_blueprint(auth) 


app.config.from_object(Config)

root_db.init_app(app)

migrate= Migrate(app, root_db)

login_manager.init_app(app)
login_manager.login_view = 'auth.signin'

ma.init_app(app)

CORS(app)

surfboard_inventory/authentication/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from surfboard_inventory.forms import UserLoginForm
from surfboard_inventory.models import User, db, check_password_hash

from flask_login import login_user, logout_user, current_user, login_required

auth = Blueprint('auth', __name__, template_folder = 'auth_templates')

@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = UserLoginForm()
    try:
        if request.method == "POST" and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            print(email, password)

            user = User(email, password = password)

            db.session.add(user)
            db.session.commit()

            flash(f"You have succesfully created a user account {email}", 'user-created')

            return redirect(url_for('auth.signin'))
    except:
        raise Exception('Invalid Form Data: Please Check Your Form')   

    
    return render_template('signup.html', form=form)

@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserLoginForm()

    try:
        if request.method == "POST" and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            print(email, password)

            logged_user = User.query.filter(User.email == email).first()
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                flash('You were succesfully login in via Email/Password', 'auth-success')
                return redirect(url_for('site.profile'))
            
            else:
                flash('Your Email/Password is incorrect', 'auth-failed')
                return redirect(url_for('auth.signin'))
    except:
        raise Exception('Invalid Form Data: Please Check Your Form')

    return render_template('signin.html', form=form)


@auth.route('/logout')
@login_required # decorator
def logout():
    logout_user()
    return redirect(url_for('site.home'))

surfboard_inventory/site/routes.py
from flask import Blueprint, render_template
from flask_login.utils import login_required
site = Blueprint('site', __name__, template_folder = 'site_templates')

@site.route('/')
def home():
    return render_template('index.html')


@site.route('/profile')
@login_required
def profile():
    return render_template('profile.html') 

surfboard_inventory/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">

<title>Title</title>
</head>
<body>
    <nav class="ct-nav">
        <div><img src="../static/css/images/surfboard_icon.svg" alt="surf-logo">
        </div>
        
        <!-- Nav Items Here -->
        <div>
            <ul id="horizontal-list">
                <a href="{{ url_for('site.home') }}">
                    <li>The Coding Drones Project</li>
                </a>
                <a href="#">
                    <li>Donate</li>
                </a>
                
                {% if current_user.is_authenticated %}
                <a href="{{ url_for('site.profile') }}">
                    <li>Profile</li>
                </a>
                <a href="{{ url_for('auth.logout') }}">
                    <li>Log Out</li>
                </a>
                {% else %}
                <a href="{{ url_for('auth.signin') }}">
                    <li>Sign-In</li>
                </a>
                <a href="{{ url_for('auth.signup') }}">
                    <li>Sign-Up</li>
                </a>
                {% endif %}
            </ul>
        </div>
    </nav>
    <!-- End of Navbar -->

    {% block content %}

    {% endblock content %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

surfboard_inventory/templates/forms.html
<form method = "POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = "form-control", placeholder= "Enter email here...") }}
        </fieldset>
        <fieldset id="pass-field">
            {{ form.password.label}}
            {{ form.password(class= "form-control", placeholder= "Enter password here...")}}
        </fieldset>
        
        <!-- submit button -->
        {{ form.submit_button(class="btn btn-info btn-block") }}
    </div>
</form>